spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${DB_PORT:5434}/${POSTGRES_DB:db_eventos}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true

openapi:
  service:
    title: Pass-in
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /events/v3/api-docs
  swagger-ui:
    path: /events/swagger-ui.html